### ISSUE TITLE
🐞 결과 공유 하기 & 링크 복사 => 둘다 링크 타고 들어가면 네트워크 에러 발생

### ISSUE THREAD

**Issue by iQuQi** [boostcampwm2023/web09-MagicConch#382]
## Description
설명을 작성하세요

## How to reproduce it
버그를 재현하는 방법을 작성하세요

## Todo
- [ ] todo
- [ ] todo

## ETC
기타 사항

**Comment by Doosies** [comment]
해당 버그가 재현되지 않아서 이슈 닫음.
